// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const BrowserSyncPlugin = require( 'browser-sync-webpack-plugin' );
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );

// Utilities.
const path = require( 'path' );

// Config settings.
const settings = require(
    path.resolve( process.cwd(), './webpack.settings.js' )
);

// Add any a new entry point by extending the webpack config.
module.exports = {
    ...defaultConfig,
    ...{
        entry: {
            'js/main': path.resolve( process.cwd(), 'js', 'main.js' ),
            'js/editor': path.resolve( process.cwd(), 'js', 'editor.js' ),
            'css/theme': path.resolve( process.cwd(), 'scss', 'theme.scss' ),
            'css/editor': path.resolve( process.cwd(), 'scss', 'editor.scss' ),
            'css/editor-overrides': path.resolve(
                process.cwd(),
                'scss',
                'editor-overrides.scss'
            ),
        },
        plugins: [
            // Include WP's plugin config.
            ...defaultConfig.plugins,
            // BrowserSync.
            new BrowserSyncPlugin( settings.browserSyncSettings, {
                injectCss: true,
                reload: true,
            } ),
            // Removes the empty `.js` files generated by webpack but
            // sets it after WP has generated its `*.asset.php` file.
            new RemoveEmptyScriptsPlugin( {
                stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
            } ),
        ],
    },
};
